spring.application.name=loyalty-engine

spring.datasource.username=loyaltyuser
spring.datasource.password=StrongPass1233!

#spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/loyalty
payment.base-url=http://38.242.155.236:8448

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# KRA eTIMS Configuration
kra.base-url=https://sbx.kra.go.ke
kra.consumer-key=yYBkGC9SSVuvaUGHkBPGSdyA07wbXARDgzB4Q9gxoIfGyRLQ
kra.consumer-secret=AqDIXXVGoeN9TogdZyLbowv4xuibt5zceK7tbcKXGqdLcfQ5nr1zxKjBQ9eRG6DO





curl -v -X GET "https://sbx.kra.go.ke/v1/token/generate?grant_type=client_credentials" ^
--user "yYBkGC9SSVuvaUGHkBPGSdyA07wbXARDgzB4Q9gxoIfGyRLQ:AqDIXXVGoeN9TogdZyLbowv4xuibt5zceK7tbcKXGqdLcfQ5nr1zxKjBQ9eRG6DO" ^
-H "Accept: application/json"



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.show-in-view=false

#white-list client url
#client.url=http://localhost:3000,http://localhost:3001,http:localhost:8080,http://38.242.155.236,http://38.242.155.236:8080
client.url=http://localhost:3000,http://localhost:3001,http:localhost:8080,http://38.242.155.236,http://38.242.155.236:8080



#Secret Key for JWT generation and verification
#loyalty-engine.secret-key=JH7y6G9kL8sQ2vP0rY3xM5tU1wE4nV7bC9dF2gH6jK0lP8qR3sT1uW4yZ5aB7cD

#loyalty-engine.secret-key=secret-key_secret-key_secret-key_secret-key_secret-key_secret-key

loyalty-engine.secret-key=9fj3k8sL2mZxVwQ7pRtY5uHnBgF4eDcA1sWqX9cV6bN8jKpL2mZxVwQ7pRtY5uH

#server details
#server.port=8443
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-alias=mycert

#sms endpoint
loyalty-engine.send-sms-api-endpoint=https://api.mobilesasa.com/v1/send/bulk-personalized

#sms sender id
loyalty-engine.send-sms-sender-id=TRCENERGIES
#sms api key
loyalty-engine.send-sms-api-key=FGC9jIYwl0EjPKztvQMIeUIihllbnKPf6OszdeXbjDPj3KjocQrmKPdzMeue

#SMS templates to send to customers
#without the offer message at the bottom, the messages have two placeholders; :customer_name and :loyalty_points. These shall be replaced with the actual customer name and loyalty points at run-time
loyalty-engine.redeemLoyaltyPoints=Dear :customer_name, you have :loyalty_points points awarded this month. Visit our station to redeem them for Ksh :loyalty_points. This offer is available between 26th this month to 3rd next month after which it will expire. TRC energies.
loyalty-engine.reachLostCustomer=Dear :customer_name, we are worried having not seen you for the past 5 days. Visit out station to get quality products and accumulate your points.
loyalty-engine.thankYouNote=Dear :customer_name, thank you for visiting TRC energies. Your new points balance is :loyalty_points points.

#Leave this pending till approved
#loyalty-engine.offer=Dear :customer_name, :product_name now goes for :product_amount per :quantity. Visit us to enjoy this new offer!

spring.profiles.active=local