spring.application.name=loyalty-engine

server.port=8085
springdoc.swagger-ui.path=/api/v1/swagger-ui

automation.url=https://api.edteria.com/api
automation.invoice.endpoint=/invoices
automation.max.file.size.mb=10
automation.timeout.seconds=30
loyalty-engine.jwt-expiration=86400000

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=loyaltyuser
spring.datasource.password=StrongPass123!
# Payment Service Configuration
payment.base-url=http://38.242.155.236:8448
# For production, change to:
spring.jackson.serialization.fail-on-empty-beans=false

#spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/loyalty


C:\Users\Ronald>curl -v -X POST "https://sbx.kra.go.ke/checker/v1/invoice" ^
More?   -H "Authorization: Bearer suWiF5tNZr5aA38ZzurH62LqMPbd" ^
More?   -H "Content-Type: application/json" ^
More?   -H "Accept: application/json" ^
More?   -d "{\"invoiceNumber\":\"KRACU0100058659/5134\",\"invoiceDate\":\"2024-08-18\"}







spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.show-in-view=false

#white-list client url
#client.url=http://localhost:3000,http://localhost:3001,http://localhost:8080,http://38.242.155.236
client.url=http://localhost:3000,http://localhost:3001,http://localhost:8080,http://38.242.155.236,http://38.242.155.236:8080


#Secret Key for JWT generation and verification
#loyalty-engine.secret-key=secret-key_secret-key_secret-key_secret-key_secret-key_secret-key
loyalty-engine.secret-key=TrcL0y4ltyEng1n32025SuP3rS3cr3tK3yR4nd0mS3cr3tK3yNov2025StrongAndSecureKey123456
#sms endpoint
loyalty-engine.send-sms-api-endpoint=https://api.mobilesasa.com/v1/send/bulk-personalized

#sms sender id
loyalty-engine.send-sms-sender-id=TRCENERGIES
#sms api key
loyalty-engine.send-sms-api-key=FGC9jIYwl0EjPKztvQMIeUIihllbnKPf6OszdeXbjDPj3KjocQrmKPdzMeue

#SMS templates to send to customers
#without the offer message at the bottom, the messages have two placeholders; :customer_name and :loyalty_points. These shall be replaced with the actual customer name and loyalty points at run-time
loyalty-engine.redeemLoyaltyPoints=Dear :customer_name, you have :loyalty_points points awarded this month. Visit our station to redeem them for Ksh :loyalty_points. This offer is available between 26th this month to 3rd next month after which it will expire. TRC energies.
loyalty-engine.reachLostCustomer=Dear :customer_name, we are worried having not seen you for the past 5 days. Visit out station to get quality products and accumulate your points.
loyalty-engine.thankYouNote=Dear :customer_name, thank you for visiting TRC energies. Your new points balance is :loyalty_points points.

#Leave this pending till approved
#loyalty-engine.offer=Dear :customer_name, :product_name now goes for :product_amount per :quantity. Visit us to enjoy this new offer!

mpesa.consumersecret=cA5EVcfHATLSLDwOpUXxK963HQWBbwhnxqKelzVImtekEcEXS58fsEAhBOEbrD8l
mpesa.consumerkey=rRYF4EhLuqDEw0kpIjNQ5xr3bEESfFOsUzMTkiNm9gg6rnLu
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919

mpesa.shortcode=174379
mpesa.tillnumber=174379

mpesa.auth-url=https://sandbox.safaricom.co.ke/oauth/v1/generate
mpesa.callback-url=https://webhook.site/27281d99-319f-445b-b7da-5c25cf21677c
mpesa.initiate-url=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
mpesa.confirm-url=https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query

